### ISSUE TITLE
Library returns wrong values

### ISSUE THREAD

**Issue by wisentini** [sckott/habanero#159]
## Environment

```
Python   3.8.18
habanero 1.2.3
```

## Problem

When I make a request to `https://api.crossref.org/journals/2448-1904` via my web browser, the `subjects` field is:

```json
"subjects": [
    {
        "ASJC": 2505,
        "name": "Materials Chemistry"
    },
    {
        "ASJC": 2002,
        "name": "Economics and Econometrics"
    },
    {
        "ASJC": 2214,
        "name": "Media Technology"
    },
    {
        "ASJC": 1107,
        "name": "Forestry"
    }
]
```

But when I make the same request via code:

```python
crossref = Crossref(
    mailto=config['crossref']['mailto'],
    ua_string=config['crossref']['user_agent']
)

response = crossref.journals(ids='2448-1904')

print(json.dumps(response['message']['subjects'], indent=4))
```

The result is:

```json
[
    {
        "ASJC": 2700,
        "name": "General Medicine"
    }
]
```

Why is that?

**Comment by sckott** [comment]
Thanks for the issue. I was able to replicate this in python3.8 and 3.11. However, it's not a habanero issue that I know of. 

E.g., try it in a curl request on the command line ([jq is here](https://jqlang.github.io/jq/) if you want to use that, otherwise just do the curl part)

without polite pool

```
 curl https://api.crossref.org/journals/2448-1904 | jq .message.subjects

[
  {
    "ASJC": 2505,
    "name": "Materials Chemistry"
  },
  {
    "ASJC": 2002,
    "name": "Economics and Econometrics"
  },
  {
    "ASJC": 2214,
    "name": "Media Technology"
  },
  {
    "ASJC": 1107,
    "name": "Forestry"
  }
]
```

with polite pool

```
curl -H 'User-Agent: (mailto:myrmecocystus@gmail.com)' https://api.crossref.org/journals/2448-1904 | jq .message.subjects

[
  {
    "ASJC": 2700,
    "name": "General Medicine"
  }
]
```

To explain, setting your email in `mailto`  puts you in the [polite pool ](https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service). Without your email set you are in the non-polite pool. that link describes what polite pool does. 

What I think is happening is that somehow the data backing each of the pools is different somehow for this API request. I'll see if I can track it down with Crossref

**Comment by sckott** [comment]
forum question linkback https://community.crossref.org/t/polite-pol-and-non-polite-pool-data-out-of-sync-possibly/4871

**Comment by sckott** [comment]
@wisentini see update from Crossref https://community.crossref.org/t/polite-pol-and-non-polite-pool-data-out-of-sync-possibly/4871/4 they're no longer returning subjects, so im closing this
